# Generated by Django 4.0.5 on 2022-06-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spammail',
            name='Mail_Body',
        ),
        migrations.AddField(
            model_name='spammail',
            name='Email_Body',
            field=models.CharField(default='Mail classification', max_length=100),
        ),
    ]
